
services:

  homeassistant:
    container_name: home-assistant
    #image: "ghcr.io/home-assistant/home-assistant:stable"
    image: lscr.io/linuxserver/homeassistant:latest
    volumes:
      - $DOCKERDIR/home-assistant/config:/config
      - /dev/sdb1:/drives/sdb1:ro
      #- /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker.sock:/run/docker.sock
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    ports:
      - 8123:8123
    networks:
      proxy:
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
#    depends_on:
#      - homeassistant-db
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.home-assistant.entrypoints=http"
      #- "traefik.http.routers.home-assistant.rule=Host(`hassio.${DOMAIN}`)"
      #- "traefik.http.middlewares.home-assistant-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.home-assistant.middlewares=home-assistant-https-redirect"
      #- "traefik.http.routers.home-assistant-secure.entrypoints=https"
      #- "traefik.http.routers.home-assistant-secure.rule=Host(`hhassio.${DOMAIN}`)"
      #- "traefik.http.routers.home-assistant-secure.tls=true"
      #- "traefik.http.routers.home-assistant-secure.tls.certresolver=cloudflare" # change this to your cert resolver
      #- "traefik.http.routers.home-assistant-secure.service=home-assistant"
      #- "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      #- "traefik.docker.network=proxy"
      - diun.enable=true
      #- com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.monitor-only=true
#    security_opt:
#      - no-new-privileges:true


#  homeassistant-db:
#    image: docker.io/postgres:16.3
#    container_name: homeassistant-db
#    restart: unless-stopped
#    # Change that password, of course!
#    environment:
#      - POSTGRES_USER=homeassistant_user
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=homeassistant-db
#      # ensure the database gets created correctly
#      # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
#      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
#    volumes:
#      - $DOCKERDIR/home-assistant/schemas:/var/lib/postgresql/data
#    networks:
#      home-assistant:
#    labels:
#      - diun.enable=true
#      #- com.centurylinklabs.watchtower.enable=true
#      - com.centurylinklabs.watchtower.monitor-only=true
#    security_opt:
#      - no-new-privileges:true

networks:
  proxy:
    external: true
