version: "3.8"

services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - "3030:80"
    labels:
      - "diun.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: on-failure