version: "3.8"

#
# https://docs.requarks.io/install/docker
#
#
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    labels:
      - "diun.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - .env      
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/wikijs/config:/config
      - $DOCKERDIR/wikijs/data:/data
    ports:
      - 4000:3000
    restart: unless-stopped