# sources:
#   Techdox: https://www.youtube.com/watch?v=V6kHXWKwzn8&t=584s
#   TechnoTim https://www.youtube.com/watch?v=W2yZ5_sd9Hc
#
# multiple folders access
# https://www.reddit.com/r/selfhosted/comments/vxo7ga/filebrowser_multiple_directories/
#
# command 'id' gives the PUID, PGID
#
# https://filebrowser.org/installation


services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    env_file: .env
    volumes:
      - /home/docky/filebrowser:/srv
      #- /mnt/terra/:/srv/terra
      #- /mnt/wdc/:/srv/wdc
      - ${DOCKERDIR}/filebrowser/filebrowser.db:/database/filebrowser.db
      - ${DOCKERDIR}/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000 # $(id -u)
      - PGID=1000 # $(id -g)
    labels:
      - "diun.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8095:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
