###############################################
# Dozzle - log viewer
# https://dozzle.dev/
# https://hub.docker.com/r/amir20/dozzle/

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      - "diun.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - DOZZLE_USERNAME=${DOZZLE_USER}
      - DOZZLE_PASSWORD=${DOZZLE_PASSWORD}
    restart: unless-stopped
