# version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: ${PUID}:${PGID} # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      # ND_IMAGECACHESIZE: 0
      ND_COVERARTPRIORITY: "embedded, cover.*, folder.*, front.*, external"
    volumes:
      - "${DOCKERDIR}/navidrome/data:/data"
      - "/mnt/terra/music:/music:ro"
    labels:
      - "diun.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"

