#
# https://hub.docker.com/r/alexta69/metube
#

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    env_file: .env    
    ports:
      - "8088:8081"
    volumes:
      - ${DOCKERDIR}/metube/downloads:/downloads
      - ${DOCKERDIR}/metube/ssl/crt:/ssl/crt.pem
      - ${DOCKERDIR}/metube/ssl/key:/ssl/key.pem
#    environment:
#      - HTTPS=true
#      - CERTFILE=/ssl/crt.pem
#      - KEYFILE=/ssl/key.pem
