#
# https://github.com/pyload/pyload
#

services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/pyload/config:/config
      - ${DOCKERDIR}/pyload/downloads:/downloads
    ports:
      - 8087:8000
      - 9666:9666 #optional
    restart: unless-stopped
