# version: "3.8"

#
# https://hub.docker.com/_/adminer/
#

services:

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 7080:8080
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      #- ADMINER_DESIGN='nette'
      - ADMINER_DESIGN=price
    labels:
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
      # - com.centurylinklabs.watchtower.monitor-only=true
