
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    networks:
      proxy:
    ports:
      # Frontend port
      - 9080:8080
    environment:
      - TZ=${TZ}
    group_add:
      - dialout
    user: 1000:1000
    devices:
    # Make sure this matched your adapter location
    #- /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_93_3A_72-if00-port0:/dev/ttyUSB0
    labels:
      - diun.enable=true
      #- com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.monitor-only=true

networks:
  proxy:
    external: true



